"""empty message

Revision ID: 61fa422b8c01
Revises: bca4d7ed7f8e
Create Date: 2022-02-17 12:31:43.036053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fa422b8c01'
down_revision = 'bca4d7ed7f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'actual_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'actual_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
